spring.application.name=jobApp
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Required for H2 Console to work in newer Spring versions
spring.h2.console.settings.web-allow-others=true